name: Deploy

on:
  release:
    types:
      - published

jobs:
  cloudflare_worker:
    runs-on: ubuntu-latest
    name: Cloudflare Worker
    concurrency: deploy-production

    environment:
      name: production
      url: https://website-icons.camellia.app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Wrangler
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
