name: Deploy

on:
  release:
    types:
      - published

jobs:
  cloudflare_worker:
    runs-on: ubuntu-latest
    name: Cloudflare Worker
    concurrency: deploy-production

    environment:
      name: production
      url: https://website-icons.camellia.app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm dependencies
        uses: actions/cache@v3.0.4
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-production-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-production-

      - name: Install npm dependencies
        run: npm ci --production --prefer-offline

      - name: Run Wrangler
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            APP_VERSION
            ENVIRONMENT_NAME
            SENTRY_DSN
        env:
          APP_VERSION: ${{ github.event.repository.name }}@${{ github.event.release.tag_name }}
          ENVIRONMENT_NAME: production
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
