name: Deploy

on:
  release:
    types:
    - published

jobs:
  cloudflare_worker_production:
    name: CloudFlare Worker (production)
    runs-on: ubuntu-latest
    concurrency: production
    environment:
      name: production
      url: https://favicons.camellia.app

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Deploy Cloudflare Worker
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        environment: production
        secrets: |
          APP_VERSION

      env:
        APP_VERSION: ${{ github.event.repository.name }}:${{ github.event.release.tag_name }}
